PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 46.137.191.103.nip.io
    exposer: Ingress
    http: "true"
    tlsacme: "false"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
jenkins:
  Servers:
    Global: {}
istio-prod:
  istio:
    enabled: true
service1:
  hpa:
    enabled: true
  istio:
    enabled: true
    gateway: jx-istio-prod
    path: /service1
service2:
  hpa:
    enabled: true
  istio:
    enabled: true
    gateway: jx-istio-prod
    path: /service2
prow: {}
